FileVersion = 1
Dependencies = {corlib = "*"}

[Project]
Name = "ImGuiImplOpenGL3"
DefaultNamespace = "imgui_beef"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/../ImGuiBeef/dist/x64/Debug/cimgui.lib"]
