name: Generation

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
  
  
env:
    DOTNET_NOLOGO: true
    VERBOSE: true
    
    
jobs: 

  Linux:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Clone submodules
        run: git submodule update --init --recursive
      - name: Get cimgui dependencies
        run: echo "TODO"
      - name: Prepare cimgui
        run: echo "TODO"
      - name: Build cimgui
        run: |         
          rm -rf "./ImGui/dist/Debug-Linux64"
          rm -rf "./ImGui/dist/Release-Linux64"
          mkdir -p "./ImGui/dist/Debug-Linux64"
          mkdir -p "./ImGui/dist/Release-Linux64"
          cd ./cimgui/
          cmake .
          cmake -DIMGUI_STATIC=yes
          cmake --build . --config Debug
          cp -rf "./cimgui.a" "../ImGui/dist/Debug-Linux64/cimgui.a"
          cmake --build . --config Release
          cp -rf "./cimgui.a" "../ImGui/dist/Release-Linux64/cimgui.a"
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b linux-cimgui-build
          git add ./ImGui/dist/Debug-Linux64/cimgui.a ./ImGui/dist/Release-Linux64/cimgui.a
          git commit -m "Generation"        
          git push
      
  Merge:
    runs-on: ubuntu-latest
    needs: [Linux]
    steps:
      - uses: actions/checkout@v2
      - name: Merge builds
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout -b Build
          git merge origin/linux-cimgui-build
          git checkout master
          git merge --squash Build
          git commit -m "Generation"
          git push origin master          
      - name: Generate ImGui bindings
        run: |
          cd ./Generator/
          dotnet run
      - name: Push generated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout master
          git add .
          git commit -m 'imgui bindings'
          git push origin master
          
  Cleanup:
    runs-on: ubuntu-latest
    needs: [Merge]
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: cleanup branches
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git push origin -d linux-cimgui-build
          git push origin -d Build
