name: Generation

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: 
      - master

jobs:
  Generate:
    env:
      generator-project-directory: D:/a/imgui-beef/imgui-beef/Generator/
      DOTNET_NOLOGO: true
      VERBOSE: true

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Clone submodules
        run: git submodule update --init --recursive
      #- name: Generate
      #  run: dotnet run
      # working-directory: ${{env.generator-project-directory}}
      #- name: Add generated files
      #  run: git add .
      - name: List directory
        run: |
          cd .\cimgui\
          dir
          cd ..
      - name: Get cimgui dependencies
        run: Copy-item -Force -Recurse -Verbose ".\cimgui-deps\*" -Destination ".\cimgui\"
      - name: Prepare cimgui
        run: |
          ((Get-Content -path .\cimgui\CMakeLists.txt -Raw) -replace "imgui/imgui_widgets.cpp","imgui/imgui_widgets`n    imgui/examples/imgui_impl_glfw.h`n    imgui/examples/imgui_impl_glfw.cpp`n    imgui/examples/imgui_impl_opengl3.h`n    imgui/examples/imgui_impl_opengl3.cpp`n    glad/glad.h`n    glad/glad.c`n    KHR/khrplatform.h") | Set-Content -Path .\cimgui\CMakeLists.txt
          ((Get-Content .\cimgui\cimgui.cpp -Raw) -replace "#include `"cimgui.h`"","#include `"cimgui.h`"`n#include <imgui/examples/imgui_impl_opengl3.h>`n#include <imgui/examples/imgui_impl_opengl2.h>`n#include <imgui/examples/imgui_impl_glfw.h>") | Set-Content .\cimgui\cimgui.cpp
      - name: Build cimgui
        run: cmake --build .\cimgui\ --target ALL_BUILD --config Release -- /nologo /maxcpucount
      - name: Copy binaries to dist
        run: Copy-item -Force -Verbose ".\cimgui\Release\cimgui.lib" -Destination ".\ImGui\dist\x64\"
      - name: Commit and push
        run: |
          git add ImGui/dist/\*
          git commit -m "Generation"
          git push
