name: Generation

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: 
      - master

jobs:
  Generate:
    env:
      generator-project-directory: D:/a/imgui-beef/imgui-beef/Generator/
      DOTNET_NOLOGO: true
      VERBOSE: true

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Clone submodules
        run: |
          git submodule update --init
          cd .\cimgui\
          git checkout docking_inter
          git submodule update --init
      - name: Generate
        run: dotnet run
        working-directory: ${{env.generator-project-directory}}
      - name: Add generated files
        run: git add .
      - name: Get cimgui dependencies
        run: Copy-item -Force -Recurse -Verbose ".\cimgui-deps\*" -Destination ".\cimgui\"
      - name: Prepare cimgui
        run: |
          ((Get-Content -path .\cimgui\CMakeLists.txt -Raw) -replace "cimgui SHARED","cimgui STATIC") | Set-Content .\cimgui\CMakeLists.txt
          ((Get-Content -path .\cimgui\CMakeLists.txt -Raw) -replace "imgui/imgui_widgets.cpp","imgui/imgui_widgets`n    imgui/examples/imgui_impl_glfw.h`n    imgui/examples/imgui_impl_glfw.cpp`n    imgui/examples/imgui_impl_opengl3.h`n    imgui/examples/imgui_impl_opengl3.cpp`n    glad/glad.h`n    glad/glad.c`n    KHR/khrplatform.h") | Set-Content -Path .\cimgui\CMakeLists.txt
          ((Get-Content .\cimgui\cimgui.cpp -Raw) -replace "#include `"cimgui.h`"","#define CIMGUI_NO_EXPORT`n#include `"cimgui.h`"`n#include <imgui/examples/imgui_impl_opengl3.h>`n#include <imgui/examples/imgui_impl_opengl2.h>`n#include <imgui/examples/imgui_impl_glfw.h>") | Set-Content .\cimgui\cimgui.cpp
      - name: Build cimgui
        run: |
          cd .\cimgui\
          cmake .
          cmake --build . --target ALL_BUILD --config Debug -- /nologo /maxcpucount
          cmake --build . --target ALL_BUILD --config Release -- /nologo /maxcpucount
      - name: Copy binaries to dist
        run: |
          Copy-item -Force -Verbose ".\cimgui\Debug\cimgui.lib" -Destination ".\ImGui\dist\Debug-Win64\"
          Copy-item -Force -Verbose ".\cimgui\Release\cimgui.lib" -Destination ".\ImGui\dist\Release-Win64\"
      - name: Commit and push
        run: |
          git add ImGui/dist/\*
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Generation"
          git push
